// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID        int64
	Name      string
	Lastname  sql.NullString
	Dni       sql.NullString
	Email     sql.NullString
	Phone     sql.NullString
	Address   sql.NullString
	StateID   sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Payment struct {
	ID        int64
	Amount    float64
	Date      sql.NullTime
	QuotaID   int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Product struct {
	ID        int64
	Name      string
	Cost      sql.NullFloat64
	Price     sql.NullFloat64
	SaleID    int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Quota struct {
	ID        int64
	Number    int64
	Amount    float64
	DueDate   time.Time
	IsPaid    sql.NullBool
	SaleID    int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Sale struct {
	ID        int64
	Amount    float64
	IsPaid    bool
	ClientID  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type State struct {
	ID          int64
	Description string
}
