// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clients.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(id)
FROM clients
WHERE name LIKE ?
   OR lastname LIKE ?
   OR dni LIKE ?
`

type CountClientsParams struct {
	Name     string
	Lastname string
	Dni      string
}

func (q *Queries) CountClients(ctx context.Context, arg CountClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients, arg.Name, arg.Lastname, arg.Dni)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT 
  c.id, 
  c.name, 
  c.lastname, 
  c.dni, 
  c.email, 
  c.phone, 
  c.address,
  c.state_id, 
  s.id AS state_id, 
  s.description AS state_description,
  c.created_at, 
  c.updated_at
FROM clients c
INNER JOIN states s ON c.state_id = s.id
WHERE c.id = ?
`

type GetClientByIDRow struct {
	ID               int64
	Name             string
	Lastname         string
	Dni              string
	Email            sql.NullString
	Phone            sql.NullString
	Address          sql.NullString
	StateID          int64
	StateID_2        int64
	StateDescription string
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetClientByID(ctx context.Context, id int64) (GetClientByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i GetClientByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Dni,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.StateID,
		&i.StateID_2,
		&i.StateDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClients = `-- name: GetClients :many
SELECT 
  c.id,
  name, 
  lastname, 
  dni, 
  s.description AS stateDescription, 
  s.id AS stateId
FROM clients c
  INNER JOIN states s ON c.state_id = s.id
WHERE name LIKE ?
   OR lastname LIKE ?
   OR dni LIKE ?
LIMIT ? OFFSET ?
`

type GetClientsParams struct {
	Name     string
	Lastname string
	Dni      string
	Limit    int64
	Offset   int64
}

type GetClientsRow struct {
	ID               int64
	Name             string
	Lastname         string
	Dni              string
	Statedescription string
	Stateid          int64
}

func (q *Queries) GetClients(ctx context.Context, arg GetClientsParams) ([]GetClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getClients,
		arg.Name,
		arg.Lastname,
		arg.Dni,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClientsRow
	for rows.Next() {
		var i GetClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lastname,
			&i.Dni,
			&i.Statedescription,
			&i.Stateid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClient = `-- name: InsertClient :one
INSERT INTO clients
( name, lastname, dni, email, phone, address, state_id)
VALUES
(?, ?, ?, ?, ?, ?, 1)
RETURNING id, name, lastname, dni, email, phone, address, state_id, created_at, updated_at
`

type InsertClientParams struct {
	Name     string
	Lastname string
	Dni      string
	Email    sql.NullString
	Phone    sql.NullString
	Address  sql.NullString
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, insertClient,
		arg.Name,
		arg.Lastname,
		arg.Dni,
		arg.Email,
		arg.Phone,
		arg.Address,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Dni,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.StateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
