// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Client struct {
	ID        int64
	Name      string
	Lastname  string
	Dni       string
	Email     sql.NullString
	Phone     sql.NullString
	Address   sql.NullString
	StateID   int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Note struct {
	ID        int64
	Content   string
	SaleID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Payment struct {
	ID        int64
	Amount    float64
	Date      time.Time
	QuotaID   int64
	ClientID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Foreign   interface{}
}

type Product struct {
	ID        int64
	Name      string
	Cost      sql.NullFloat64
	Price     sql.NullFloat64
	Stock     int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Quota struct {
	ID        int64
	Number    int64
	Amount    float64
	DueDate   time.Time
	IsPaid    sql.NullBool
	StateID   int64
	SaleID    int64
	ClientID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Foreign   interface{}
}

type Sale struct {
	ID          int64
	Description string
	Amount      float64
	IsPaid      bool
	StateID     int64
	ClientID    int64
	Date        time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SaleProduct struct {
	ID        int64
	Name      string
	Cost      sql.NullFloat64
	Price     sql.NullFloat64
	Quantity  int64
	SaleID    int64
	ClientID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Foreign   interface{}
}

type State struct {
	ID          int64
	Description string
}
