// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payments.sql

package sqlc

import (
	"context"
)

const getQuotaPayments = `-- name: GetQuotaPayments :many
SELECT id, amount, date, quota_id, client_id, created_at, updated_at, "foreign" FROM payments WHERE quota_id = ?
`

func (q *Queries) GetQuotaPayments(ctx context.Context, quotaID int64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, getQuotaPayments, quotaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Date,
			&i.QuotaID,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Foreign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
