// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"
)

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products
SET stock = MAX(stock - ?, 0)
WHERE id = ?
`

type UpdateProductStockParams struct {
	Stock int64
	ID    int64
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.ExecContext(ctx, updateProductStock, arg.Stock, arg.ID)
	return err
}
