// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sale_products.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSaleProduct = `-- name: CreateSaleProduct :exec
INSERT INTO sale_products (name, cost, price, quantity, sale_id, client_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSaleProductParams struct {
	Name     string
	Cost     sql.NullFloat64
	Price    sql.NullFloat64
	Quantity int64
	SaleID   int64
	ClientID int64
}

func (q *Queries) CreateSaleProduct(ctx context.Context, arg CreateSaleProductParams) error {
	_, err := q.db.ExecContext(ctx, createSaleProduct,
		arg.Name,
		arg.Cost,
		arg.Price,
		arg.Quantity,
		arg.SaleID,
		arg.ClientID,
	)
	return err
}
